spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
    driverClassName: org.postgresql.Driver
server:
  port: 9090

#    url: jdbc:postgresql://${BASEPROJECT_DATABASE_HOST}:${BASEPROJECT_DATABASE_PORT}/${BASEPROJECT_DATABASE_NAME}
#    username: ${BASEPROJECT_DATABASE_USERNAME}
#    password: ${BASEPROJECT_DATABASE_PASSWORD}
#    driverClassName: org.postgresql.Driver